import { defineConfig } from "@lingui/cli";
import { formatter } from "@lingui/format-po";

import { LOCALES, PSEUDO_LOCALE } from "./src/lib/locale";

/**
 * Lingui catalog config.
 *
 * `locales` is derived from `src/lib/locale.ts` so the runtime locale list and
 * the catalog list can't drift — adding a language there is the only edit
 * needed to get catalogs for it.
 */
export default defineConfig({
  sourceLocale: "en",
  // The pseudo-locale is generated by `lingui extract --locale en-XA`, not
  // translated by hand; it exists to surface unextracted strings and to stress
  // layouts with ~30% text expansion.
  pseudoLocale: PSEUDO_LOCALE,
  locales: [...LOCALES],
  fallbackLocales: { default: "en" },
  catalogs: [
    {
      path: "<rootDir>/src/locales/{locale}/messages",
      include: ["src"],
      exclude: [
        "**/node_modules/**",
        // Generated by TanStack Router — no authored strings.
        "**/routeTree.gen.ts",
        "**/*.test.*",
        "**/*.spec.*",
        // Vendored copy-and-own design system. `vite.config.ts` excludes this
        // directory from the Babel pass that compiles Lingui macros, so any
        // macro placed here would ship untransformed and blow up at runtime.
        // Its strings are aria-labels; localize them by passing translated
        // props from callers instead.
        "src/design-system/**",
      ],
    },
  ],
  // `lineNumbers: false` keeps catalog diffs to real message changes instead of
  // churning every entry whenever unrelated lines shift.
  format: formatter({ origins: true, lineNumbers: false }),
  orderBy: "messageId",
  compileNamespace: "ts",
});
