/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'app.standard-reader.authBasicFeatures'

export { $nsid }

const main = /*#__PURE__*/ l.permissionSet(
  $nsid,
  [
    /*#__PURE__*/ l.permission('repo', {
      collection: [
        'app.standard-reader.bookmark',
        'app.standard-reader.graph.follow',
        'app.standard-reader.labelerSubscription',
        'app.standard-reader.labeler.subscription',
        'app.standard-reader.list',
        'app.standard-reader.listSave',
        'app.standard-reader.read',
        'app.standard-reader.sidebarPref',
      ],
    }),
  ],
  {
    title: 'Standard Reader',
    detail:
      'Bookmark articles, mark them read, and create and save publication lists.',
  },
)

export { main }
