/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'app.standard-reader.authCollections'

export { $nsid }

const main = /*#__PURE__*/ l.permissionSet(
  $nsid,
  [
    /*#__PURE__*/ l.permission('repo', {
      collection: [
        'app.standard-reader.collection',
        'app.standard-reader.collectionsPublication',
        'app.standard-reader.publicationTheme',
      ],
    }),
  ],
  {
    title: 'Standard Reader Collection Publications',
    detail:
      'Create and manage Collections within the app. A Collection is a meta publication that composes other documents along with your personal narrative.',
  },
)

export { main }
