/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.getAuthor'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  did: /*#__PURE__*/ l.string({ format: 'did' }),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  profile: /*#__PURE__*/ l.ref<StandardReaderDefs.ProfileView>(
    (() => StandardReaderDefs.profileView) as any,
  ),
  stats: /*#__PURE__*/ l.ref<Stats>((() => stats) as any),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Author profile for a DID with aggregate stats. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid

/** Aggregate author counts shown on the profile header. */
type Stats = {
  $type?: 'app.standard-reader.getAuthor#stats'
  publicationCount?: number
  documentCount?: number
  subscriberCount?: number
  followingCount?: number
  likeCount?: number
}

export type { Stats }

/** Aggregate author counts shown on the profile header. */
const stats = /*#__PURE__*/ l.typedObject<Stats>(
  $nsid,
  'stats',
  /*#__PURE__*/ l.object({
    publicationCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    documentCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    subscriberCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    followingCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    likeCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  }),
)

export { stats }
