/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.getList'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  list: /*#__PURE__*/ l.string({ format: 'at-uri' }),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  uri: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'at-uri' })),
  name: /*#__PURE__*/ l.string({ maxLength: 128 }),
  description: /*#__PURE__*/ l.nullable(l.optional(
    /*#__PURE__*/ l.string({ maxLength: 4096 }),
  )),
  publications: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<StandardReaderDefs.PublicationView>(
      (() => StandardReaderDefs.publicationView) as any,
    ),
  ),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Public metadata and member publications for an app.standard-reader.list AT-URI. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
