/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.getPublication'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  publication: /*#__PURE__*/ l.string({ format: 'at-uri' }),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  publication: /*#__PURE__*/ l.ref<StandardReaderDefs.PublicationView>(
    (() => StandardReaderDefs.publicationView) as any,
  ),
  owner: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.ref<StandardReaderDefs.ProfileView>(
      (() => StandardReaderDefs.profileView) as any,
    ),
  ),
  subscriberCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  documentCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  lastDocumentAt: /*#__PURE__*/ l.nullable(l.optional(
    /*#__PURE__*/ l.string({ format: 'datetime' }),
  )),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Fetch a single publication profile with owner identity and aggregate stats. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
