/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'app.standard-reader.publicationTheme'

export { $nsid }

/** Standard Reader typography for a collections publication. Uses the same record key as the publication. Colors remain on the publication's site.standard.theme.basic record. */
type Main = {
  $type: 'app.standard-reader.publicationTheme'

  /**
   * AT URI of the site.standard.publication this theme applies to.
   */
  publication: l.AtUriString
  fonts?: Fonts

  /**
   * When the theme record was first published.
   */
  createdAt: l.DatetimeString

  /**
   * When the theme record was last edited.
   */
  updatedAt?: l.DatetimeString
}

export type { Main }

/** Standard Reader typography for a collections publication. Uses the same record key as the publication. Colors remain on the publication's site.standard.theme.basic record. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    publication: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    fonts: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Fonts>((() => fonts) as any),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    updatedAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Google Font family names for collection title and body typography. */
type Fonts = {
  $type?: 'app.standard-reader.publicationTheme#fonts'
  title?: string
  body?: string
}

export type { Fonts }

/** Google Font family names for collection title and body typography. */
const fonts = /*#__PURE__*/ l.typedObject<Fonts>(
  $nsid,
  'fonts',
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 60 })),
    body: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 60 })),
  }),
)

export { fonts }
