/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.resolveHandle'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  handle: /*#__PURE__*/ l.string({ maxLength: 128 }),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  did: /*#__PURE__*/ l.nullable(l.optional(/*#__PURE__*/ l.string({ format: 'did' }))),
  handle: /*#__PURE__*/ l.nullable(l.optional(/*#__PURE__*/ l.string({ maxLength: 128 }))),
  publications: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<StandardReaderDefs.PublicationView>(
      (() => StandardReaderDefs.publicationView) as any,
    ),
  ),
  source: /*#__PURE__*/ l.string<{
    knownValues: ['index', 'repo', 'none']
    maxLength: 32
  }>({ maxLength: 32 }),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Resolve an AT Proto handle, domain, or DID to site.standard.publication previews. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
