import * as stylex from "@stylexjs/stylex";

import { animationDuration } from "#/design-system/theme/animations.stylex";
import { primaryColor, uiColor } from "#/design-system/theme/color.stylex";
import { radius } from "#/design-system/theme/radius.stylex";
import {
  gap,
  horizontalSpace,
  verticalSpace,
} from "#/design-system/theme/semantic-spacing.stylex";
import { spacing } from "#/design-system/theme/spacing.stylex";
import {
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
} from "#/design-system/theme/typography.stylex";

export const commentStyles = stylex.create({
  section: {
    boxSizing: "border-box",
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "80ch",
    paddingBottom: spacing["20"],
    paddingLeft: spacing["6"],
    paddingRight: spacing["6"],
    width: "100%",
  },
  list: {
    gap: gap.lg,
    display: "flex",
    flexDirection: "column",
    marginTop: verticalSpace.lg,
  },
  card: {
    borderColor: uiColor.border1,
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: 1,
    cornerShape: "squircle",
    backgroundColor: uiColor.component1,
    color: "inherit",
    display: "block",
    paddingBottom: verticalSpace.lg,
    paddingLeft: horizontalSpace.lg,
    paddingRight: horizontalSpace.lg,
    paddingTop: verticalSpace.lg,
  },
  cardBodyLink: {
    borderRadius: radius.sm,
    textDecoration: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": uiColor.component2,
    },
    color: "inherit",
    display: "block",
    transitionDuration: animationDuration.fast,
    transitionProperty: "background-color",
    marginLeft: `calc(-1 * ${horizontalSpace.lg})`,
    marginRight: `calc(-1 * ${horizontalSpace.lg})`,
    paddingBottom: verticalSpace.lg,
    paddingLeft: horizontalSpace.lg,
    paddingRight: horizontalSpace.lg,
    paddingTop: verticalSpace.md,
  },
  cardHeader: {
    alignItems: "center",
    columnGap: gap.md,
    display: "flex",
    rowGap: gap.md,
    marginBottom: verticalSpace.md,
  },
  authorLink: {
    textDecoration: "none",
    alignItems: "center",
    color: "inherit",
    columnGap: gap.md,
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    rowGap: gap.md,
    minWidth: 0,
  },
  authorMeta: {
    gap: gap.xs,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  authorName: {
    overflow: "hidden",
    color: uiColor.text2,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  authorHandle: {
    color: uiColor.text1,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.xs,
  },
  timestamp: {
    color: uiColor.text1,
    flexShrink: 0,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    marginLeft: "auto",
  },
  blockquote: {
    color: uiColor.text2,
    fontFamily: fontFamily.serif,
    fontSize: fontSize.lg,
    fontStyle: "italic",
    lineHeight: lineHeight.sm,
    borderLeftColor: primaryColor.solid1,
    borderLeftStyle: "solid",
    borderLeftWidth: spacing["1"],
    marginBottom: verticalSpace.md,
    marginLeft: horizontalSpace.none,
    marginRight: horizontalSpace.none,
    marginTop: spacing["0"],
    paddingLeft: horizontalSpace.md,
  },
  commentary: {
    gap: gap.sm,
    display: "flex",
    flexDirection: "column",
    marginBottom: verticalSpace.md,
    marginTop: spacing["0"],
  },
  commentaryParagraph: {
    color: uiColor.text2,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.base,
    lineHeight: lineHeight.base,
    whiteSpace: "pre-line",
    marginBottom: spacing["0"],
    marginTop: spacing["0"],
  },
  facetMentionLink: {
    textDecoration: { default: "none", ":hover": "underline" },
    color: "inherit",
    textDecorationColor: "currentColor",
    textUnderlineOffset: "2px",
  },
  facetLink: {
    textDecoration: { default: "underline", ":hover": "none" },
    color: primaryColor.text2,
    textUnderlineOffset: "2px",
  },
  facetBold: {
    fontWeight: fontWeight.semibold,
  },
  facetItalic: {
    fontStyle: "italic",
  },
  facetCode: {
    borderRadius: radius.sm,
    cornerShape: "squircle",
    backgroundColor: uiColor.component2,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    paddingBottom: spacing["0.5"],
    paddingLeft: spacing["1.5"],
    paddingRight: spacing["1.5"],
    paddingTop: spacing["0.5"],
  },
  footer: {
    alignItems: "center",
    color: uiColor.text1,
    columnGap: gap.sm,
    display: "flex",
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    rowGap: gap.sm,
  },
  empty: {
    color: uiColor.text1,
    fontFamily: fontFamily.serif,
    fontSize: fontSize.lg,
    fontStyle: "italic",
    textAlign: "center",
    marginTop: verticalSpace.lg,
  },
  skeleton: {
    borderColor: uiColor.border1,
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: 1,
    cornerShape: "squircle",
    backgroundColor: uiColor.component1,
    height: spacing["24"],
  },
});
