/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'

const $nsid = 'app.standard-reader.labeler.defs'

export { $nsid }

type LabelerPolicies = {
  $type?: 'app.standard-reader.labeler.defs#labelerPolicies'

  /**
   * The label values which this labeler publishes. May include global or custom (labeler-defined) values.
   */
  labelValues: LabelDefs.LabelValue[]

  /**
   * Label values created by this labeler and scoped exclusively to it. Each value provides its own meaning and behaviors.
   */
  labelValueDefinitions?: LabelDefs.LabelValueDefinition[]
}

export type { LabelerPolicies }

const labelerPolicies = /*#__PURE__*/ l.typedObject<LabelerPolicies>(
  $nsid,
  'labelerPolicies',
  /*#__PURE__*/ l.object({
    labelValues: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<LabelDefs.LabelValue>(
        (() => LabelDefs.labelValue) as any,
      ),
    ),
    labelValueDefinitions: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<LabelDefs.LabelValueDefinition>(
          (() => LabelDefs.labelValueDefinition) as any,
        ),
      ),
    ),
  }),
)

export { labelerPolicies }

type LabelerView = {
  $type?: 'app.standard-reader.labeler.defs#labelerView'
  did: l.DidString
  displayName?: string
  description?: string
  avatar?: l.UriString
  policies?: LabelerPolicies
  indexedAt?: l.DatetimeString
}

export type { LabelerView }

const labelerView = /*#__PURE__*/ l.typedObject<LabelerView>(
  $nsid,
  'labelerView',
  /*#__PURE__*/ l.object({
    did: /*#__PURE__*/ l.string({ format: 'did' }),
    displayName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 64, maxLength: 640 }),
    ),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxGraphemes: 300, maxLength: 3000 }),
    ),
    avatar: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'uri' })),
    policies: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<LabelerPolicies>((() => labelerPolicies) as any),
    ),
    indexedAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { labelerView }
