/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'app.standard-reader.labeler.subscription'

export { $nsid }

/** Subscribes the reader to a labeler service (like adding a Bluesky moderation service). Presence of the record means subscribed; deleting it unsubscribes. The rkey is derived from the labeler DID so each labeler maps to a single record. Successor to app.standard-reader.labelerSubscription, nested under the labeler NSID group. */
type Main = {
  $type: 'app.standard-reader.labeler.subscription'

  /**
   * DID of the labeler service being subscribed to.
   */
  labeler: l.DidString

  /**
   * Per-label visibility overrides for this labeler's label values.
   */
  labels?: LabelPref[]

  /**
   * When the reader subscribed to the labeler.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Subscribes the reader to a labeler service (like adding a Bluesky moderation service). Presence of the record means subscribed; deleting it unsubscribes. The rkey is derived from the labeler DID so each labeler maps to a single record. Successor to app.standard-reader.labelerSubscription, nested under the labeler NSID group. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    labeler: /*#__PURE__*/ l.string({ format: 'did' }),
    labels: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<LabelPref>((() => labelPref) as any),
      ),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** How the reader wants a single label value from this labeler treated. */
type LabelPref = {
  $type?: 'app.standard-reader.labeler.subscription#labelPref'

  /**
   * The label value this preference applies to.
   */
  val: string

  /**
   * ignore = show normally; warn = content warning / blur; hide = filter out.
   */
  visibility: 'ignore' | 'warn' | 'hide' | l.UnknownString
}

export type { LabelPref }

/** How the reader wants a single label value from this labeler treated. */
const labelPref = /*#__PURE__*/ l.typedObject<LabelPref>(
  $nsid,
  'labelPref',
  /*#__PURE__*/ l.object({
    val: /*#__PURE__*/ l.string({ maxLength: 128 }),
    visibility: /*#__PURE__*/ l.string<{
      maxLength: 16
      knownValues: ['ignore', 'warn', 'hide']
    }>({ maxLength: 16 }),
  }),
)

export { labelPref }
