/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as MarkpubMarkdown from '../../at/markpub/markdown.defs.js'

const $nsid = 'app.standard-reader.collection'

export { $nsid }

/** Curated magazine collection manifest for a site.standard.document. Uses the same record key as the document it extends so both records can be fetched with one predictable pair of GETs. */
type Main = {
  $type: 'app.standard-reader.collection'

  /**
   * AT URI of the site.standard.document record this collection renders.
   */
  document: l.AtUriString
  editorial?: Editorial
  colophon?: Colophon

  /**
   * Ordered curated articles plus optional per-item notes.
   */
  items: Item[]

  /**
   * When the collection manifest was first published.
   */
  createdAt: l.DatetimeString

  /**
   * When the collection manifest was last edited.
   */
  updatedAt?: l.DatetimeString
}

export type { Main }

/** Curated magazine collection manifest for a site.standard.document. Uses the same record key as the document it extends so both records can be fetched with one predictable pair of GETs. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    document: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    editorial: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Editorial>((() => editorial) as any),
    ),
    colophon: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Colophon>((() => colophon) as any),
    ),
    items: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<Item>((() => item) as any),
      { maxLength: 42 },
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    updatedAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Optional editorial intro shown ahead of the curated pieces. */
type Editorial = {
  $type?: 'app.standard-reader.collection#editorial'
  title?: string

  /**
   * Editorial body as Markpub markdown (legacy plain string accepted on read during migration).
   */
  body?: l.$Typed<MarkpubMarkdown.Main> | l.Unknown$TypedObject
}

export type { Editorial }

/** Optional editorial intro shown ahead of the curated pieces. */
const editorial = /*#__PURE__*/ l.typedObject<Editorial>(
  $nsid,
  'editorial',
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 160 })),
    body: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<MarkpubMarkdown.Main>(
            (() => MarkpubMarkdown.main) as any,
          ),
        ],
        false,
      ),
    ),
  }),
)

export { editorial }

/** Optional closing credits on the magazine end spread. */
type Colophon = {
  $type?: 'app.standard-reader.collection#colophon'

  /**
   * Colophon body as Markpub markdown (legacy plain string accepted on read during migration).
   */
  body?: l.$Typed<MarkpubMarkdown.Main> | l.Unknown$TypedObject
}

export type { Colophon }

/** Optional closing credits on the magazine end spread. */
const colophon = /*#__PURE__*/ l.typedObject<Colophon>(
  $nsid,
  'colophon',
  /*#__PURE__*/ l.object({
    body: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<MarkpubMarkdown.Main>(
            (() => MarkpubMarkdown.main) as any,
          ),
        ],
        false,
      ),
    ),
  }),
)

export { colophon }

type Item = {
  $type?: 'app.standard-reader.collection#item'

  /**
   * AT URI of an included site.standard.document.
   */
  document: l.AtUriString

  /**
   * Optional Markpub markdown note shown ahead of the piece (legacy plain string accepted on read during migration).
   */
  note?: l.$Typed<MarkpubMarkdown.Main> | l.Unknown$TypedObject
}

export type { Item }

const item = /*#__PURE__*/ l.typedObject<Item>(
  $nsid,
  'item',
  /*#__PURE__*/ l.object({
    document: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    note: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.typedUnion(
        [
          /*#__PURE__*/ l.typedRef<MarkpubMarkdown.Main>(
            (() => MarkpubMarkdown.main) as any,
          ),
        ],
        false,
      ),
    ),
  }),
)

export { item }

/** Inverse link entry for site.standard.document#links pointing back at this collection sidecar. */
type DocumentLink = {
  $type?: 'app.standard-reader.collection#documentLink'

  /**
   * AT URI of the app.standard-reader.collection sidecar record.
   */
  uri: l.AtUriString
}

export type { DocumentLink }

/** Inverse link entry for site.standard.document#links pointing back at this collection sidecar. */
const documentLink = /*#__PURE__*/ l.typedObject<DocumentLink>(
  $nsid,
  'documentLink',
  /*#__PURE__*/ l.object({ uri: /*#__PURE__*/ l.string({ format: 'at-uri' }) }),
)

export { documentLink }
