/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'app.standard-reader.defs'

export { $nsid }

/** A publication as shown in directory cards and profile headers. */
type PublicationView = {
  $type?: 'app.standard-reader.defs#publicationView'
  uri: l.AtUriString
  did: l.DidString
  name: string
  url: l.UriString
  description?: string
  iconUrl?: l.UriString
  ownerAvatarUrl?: l.UriString
  ownerHandle?: string
  topic?: string
  verified?: boolean
  subscriberCount: number
  documentCount: number
  lastDocumentAt?: l.DatetimeString
  searchNameHtml?: string
  searchSnippetHtml?: string
}

export type { PublicationView }

/** A publication as shown in directory cards and profile headers. */
const publicationView = /*#__PURE__*/ l.typedObject<PublicationView>(
  $nsid,
  'publicationView',
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    did: /*#__PURE__*/ l.string({ format: 'did' }),
    name: /*#__PURE__*/ l.string({ maxLength: 128 }),
    url: /*#__PURE__*/ l.string({ format: 'uri' }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 4096 }),
    ),
    iconUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    ownerAvatarUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    ownerHandle: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    topic: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 128 })),
    verified: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    subscriberCount: /*#__PURE__*/ l.integer(),
    documentCount: /*#__PURE__*/ l.integer(),
    lastDocumentAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    searchNameHtml: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 512 }),
    ),
    searchSnippetHtml: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 8192 }),
    ),
  }),
)

export { publicationView }

/** An article as shown in feed rows and search results (metadata only). */
type DocumentView = {
  $type?: 'app.standard-reader.defs#documentView'
  uri: l.AtUriString
  did: l.DidString
  title: string
  description?: string
  path?: string
  canonicalUrl?: l.UriString
  coverImageUrl?: l.UriString
  publishedAt: l.DatetimeString
  featured?: boolean
  publicationUri?: l.AtUriString
  publicationName?: string
  publicationIconUrl?: l.UriString
  publicationOwnerAvatarUrl?: l.UriString
  publicationOwnerHandle?: string
  publicationBannerUrl?: l.UriString
  publicationTopic?: string
  tags?: string[]
  recommendCount: number
  commentCount: number
  hasRenderableBody: boolean
  isRead: boolean
  searchTitleHtml?: string
  searchSnippetHtml?: string
}

export type { DocumentView }

/** An article as shown in feed rows and search results (metadata only). */
const documentView = /*#__PURE__*/ l.typedObject<DocumentView>(
  $nsid,
  'documentView',
  /*#__PURE__*/ l.object({
    uri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    did: /*#__PURE__*/ l.string({ format: 'did' }),
    title: /*#__PURE__*/ l.string({ maxLength: 512 }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 4096 }),
    ),
    path: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 2048 })),
    canonicalUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    coverImageUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    publishedAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    featured: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    publicationUri: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
    ),
    publicationName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    publicationIconUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    publicationOwnerAvatarUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    publicationOwnerHandle: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    publicationBannerUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    publicationTopic: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    tags: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxLength: 128 })),
    ),
    recommendCount: /*#__PURE__*/ l.integer(),
    commentCount: /*#__PURE__*/ l.integer(),
    hasRenderableBody: /*#__PURE__*/ l.boolean(),
    isRead: /*#__PURE__*/ l.boolean(),
    searchTitleHtml: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 1024 }),
    ),
    searchSnippetHtml: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 8192 }),
    ),
  }),
)

export { documentView }

type ProfileView = {
  $type?: 'app.standard-reader.defs#profileView'
  did: l.DidString
  handle?: string
  displayName?: string
  description?: string
  avatarUrl?: l.UriString
  bannerUrl?: l.UriString
}

export type { ProfileView }

const profileView = /*#__PURE__*/ l.typedObject<ProfileView>(
  $nsid,
  'profileView',
  /*#__PURE__*/ l.object({
    did: /*#__PURE__*/ l.string({ format: 'did' }),
    handle: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    displayName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 4096 }),
    ),
    avatarUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    bannerUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
  }),
)

export { profileView }

type CursorPagePublications = {
  $type?: 'app.standard-reader.defs#cursorPagePublications'
  cursor?: string
  items: PublicationView[]
}

export type { CursorPagePublications }

const cursorPagePublications =
  /*#__PURE__*/ l.typedObject<CursorPagePublications>(
    $nsid,
    'cursorPagePublications',
    /*#__PURE__*/ l.object({
      cursor: /*#__PURE__*/ l.optional(
        /*#__PURE__*/ l.string({ maxLength: 8192 }),
      ),
      items: /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<PublicationView>((() => publicationView) as any),
      ),
    }),
  )

export { cursorPagePublications }

type CursorPageDocuments = {
  $type?: 'app.standard-reader.defs#cursorPageDocuments'
  cursor?: string
  items: DocumentView[]
}

export type { CursorPageDocuments }

const cursorPageDocuments = /*#__PURE__*/ l.typedObject<CursorPageDocuments>(
  $nsid,
  'cursorPageDocuments',
  /*#__PURE__*/ l.object({
    cursor: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 8192 }),
    ),
    items: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<DocumentView>((() => documentView) as any),
    ),
  }),
)

export { cursorPageDocuments }

type ResolveViewArticle = {
  $type?: 'app.standard-reader.defs#resolveViewArticle'
  kind: 'article'
  documentUri: l.AtUriString
  title: string
  publicationUri?: l.AtUriString
  publicationName?: string
  publicationHandle?: string
  publicationIconUrl?: l.UriString
  publicationOwnerAvatarUrl?: l.UriString
  publicationSubscriberCount?: number
  publicationReaderUrl?: l.UriString
  publishedAt?: l.DatetimeString
  readingMinutes?: number
  authorName?: string
  authorHandle?: string
  authorAvatarUrl?: l.UriString
  readerUrl: l.UriString
  canonicalUrl?: l.UriString
  isBookmarked?: boolean
  isRead?: boolean
  isFollowing?: boolean
  recommendCount: number
  commentCount: number
}

export type { ResolveViewArticle }

const resolveViewArticle = /*#__PURE__*/ l.typedObject<ResolveViewArticle>(
  $nsid,
  'resolveViewArticle',
  /*#__PURE__*/ l.object({
    kind: /*#__PURE__*/ l.literal('article'),
    documentUri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    title: /*#__PURE__*/ l.string({ maxLength: 512 }),
    publicationUri: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
    ),
    publicationName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    publicationHandle: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    publicationIconUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    publicationOwnerAvatarUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    publicationSubscriberCount: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer(),
    ),
    publicationReaderUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    publishedAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    readingMinutes: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
    authorName: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    authorHandle: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 128 }),
    ),
    authorAvatarUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    readerUrl: /*#__PURE__*/ l.string({ format: 'uri' }),
    canonicalUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    isBookmarked: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    isRead: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    isFollowing: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    recommendCount: /*#__PURE__*/ l.integer(),
    commentCount: /*#__PURE__*/ l.integer(),
  }),
)

export { resolveViewArticle }

type ResolveViewPublication = {
  $type?: 'app.standard-reader.defs#resolveViewPublication'
  kind: 'publication'
  publicationUri: l.AtUriString
  name: string
  description?: string
  handle?: string
  iconUrl?: l.UriString
  ownerAvatarUrl?: l.UriString
  subscriberCount?: number
  readerUrl: l.UriString
  siteUrl?: l.UriString
  isFollowing?: boolean
}

export type { ResolveViewPublication }

const resolveViewPublication =
  /*#__PURE__*/ l.typedObject<ResolveViewPublication>(
    $nsid,
    'resolveViewPublication',
    /*#__PURE__*/ l.object({
      kind: /*#__PURE__*/ l.literal('publication'),
      publicationUri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
      name: /*#__PURE__*/ l.string({ maxLength: 128 }),
      description: /*#__PURE__*/ l.optional(
        /*#__PURE__*/ l.string({ maxLength: 4096 }),
      ),
      handle: /*#__PURE__*/ l.optional(
        /*#__PURE__*/ l.string({ maxLength: 128 }),
      ),
      iconUrl: /*#__PURE__*/ l.optional(
        /*#__PURE__*/ l.string({ format: 'uri' }),
      ),
      ownerAvatarUrl: /*#__PURE__*/ l.optional(
        /*#__PURE__*/ l.string({ format: 'uri' }),
      ),
      subscriberCount: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
      readerUrl: /*#__PURE__*/ l.string({ format: 'uri' }),
      siteUrl: /*#__PURE__*/ l.optional(
        /*#__PURE__*/ l.string({ format: 'uri' }),
      ),
      isFollowing: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    }),
  )

export { resolveViewPublication }

type ResolveViewReaderLink = {
  $type?: 'app.standard-reader.defs#resolveViewReaderLink'
  kind: 'reader-link'
  readerUrl: l.UriString
}

export type { ResolveViewReaderLink }

const resolveViewReaderLink =
  /*#__PURE__*/ l.typedObject<ResolveViewReaderLink>(
    $nsid,
    'resolveViewReaderLink',
    /*#__PURE__*/ l.object({
      kind: /*#__PURE__*/ l.literal('reader-link'),
      readerUrl: /*#__PURE__*/ l.string({ format: 'uri', maxLength: 2048 }),
    }),
  )

export { resolveViewReaderLink }

type ResolveViewUnknown = {
  $type?: 'app.standard-reader.defs#resolveViewUnknown'
  kind: 'unknown'
}

export type { ResolveViewUnknown }

const resolveViewUnknown = /*#__PURE__*/ l.typedObject<ResolveViewUnknown>(
  $nsid,
  'resolveViewUnknown',
  /*#__PURE__*/ l.object({ kind: /*#__PURE__*/ l.literal('unknown') }),
)

export { resolveViewUnknown }
