/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.getDocumentContext'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  document: /*#__PURE__*/ l.string({ format: 'at-uri' }),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  moreFrom: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<StandardReaderDefs.DocumentView>(
        (() => StandardReaderDefs.documentView) as any,
      ),
    ),
  ),
  related: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<StandardReaderDefs.DocumentView>(
        (() => StandardReaderDefs.documentView) as any,
      ),
    ),
  ),
  readersAlsoFollow: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<StandardReaderDefs.PublicationView>(
        (() => StandardReaderDefs.publicationView) as any,
      ),
    ),
  ),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Deferred reading-view context: related articles, recents, social proof, citations. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
