/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.getHomeFeed'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  scope: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.string<{
        knownValues: ['subscriptions', 'all']
        maxLength: 32
      }>({ maxLength: 32 }),
      'subscriptions',
    ),
  ),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  featured: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.ref<StandardReaderDefs.DocumentView>(
      (() => StandardReaderDefs.documentView) as any,
    ),
  ),
  latest: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<StandardReaderDefs.DocumentView>(
        (() => StandardReaderDefs.documentView) as any,
      ),
    ),
  ),
  scope: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 32 })),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Signed-in home page critical path: featured lead and latest rows. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
