/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as LabelerDefs from './labeler/defs.defs.js'

const $nsid = 'app.standard-reader.getLabeler'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  actor: /*#__PURE__*/ l.string({ format: 'at-identifier' }),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  labeler: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.ref<LabelerDefs.LabelerView>(
      (() => LabelerDefs.labelerView) as any,
    ),
  ),
  subscribed: /*#__PURE__*/ l.boolean(),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Resolve a single labeler by DID or handle (for previewing before subscribing), with the calling reader's subscription state. Discovered the standard way via the DID document's #atproto_labeler service. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
