/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as LabelerDefs from './labeler/defs.defs.js'

const $nsid = 'app.standard-reader.getLabelers'

export { $nsid }

export const $params = /*#__PURE__*/ l.params()

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  labelers: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<LabelerDefs.LabelerView>(
      (() => LabelerDefs.labelerView) as any,
    ),
  ),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** List the labelers the calling reader is subscribed to, each resolved (the standard way) to a labeler view. Used by the Settings → Labelers page. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
