/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.getPublications'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  topic: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 128 })),
  sort: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.string<{
        knownValues: ['readers', 'active', 'az']
        maxLength: 32
      }>({ maxLength: 32 }),
      'readers',
    ),
  ),
  limit: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 60 }),
      24,
    ),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 8192 })),
  q: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 256 })),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.payload(
  'application/json',
  /*#__PURE__*/ l.ref<StandardReaderDefs.CursorPagePublications>(
    (() => StandardReaderDefs.cursorPagePublications) as any,
  ),
)

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Browse the publication directory with topic filter, sort, and cursor pagination. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
