/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.getTagFeed'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  tag: /*#__PURE__*/ l.string({ maxLength: 128 }),
  view: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.string<{
        knownValues: ['articles', 'publications']
        maxLength: 32
      }>({ maxLength: 32 }),
      'articles',
    ),
  ),
  sort: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 32 })),
  limit: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 50 }),
      20,
    ),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 8192 })),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  view: /*#__PURE__*/ l.string({ maxLength: 32 }),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 8192 })),
  items: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.typedUnion(
      [
        /*#__PURE__*/ l.typedRef<StandardReaderDefs.PublicationView>(
          (() => StandardReaderDefs.publicationView) as any,
        ),
        /*#__PURE__*/ l.typedRef<StandardReaderDefs.DocumentView>(
          (() => StandardReaderDefs.documentView) as any,
        ),
      ],
      false,
    ),
  ),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Articles or publications carrying a given tag. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
