/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'

const $nsid = 'app.standard-reader.list'

export { $nsid }

/** A named, ordered, shareable list of publications (like a Bluesky user list, but for site.standard.publication subscriptions). Lists are one level deep; a publication may appear in multiple lists. */
type Main = {
  $type: 'app.standard-reader.list'

  /**
   * Display name of the list.
   */
  name: string

  /**
   * Optional description shown on the list's public page.
   */
  description?: string

  /**
   * Ordered AT URIs of the site.standard.publication records in this list.
   */
  publications: l.AtUriString[]

  /**
   * Ordered DIDs of the users (authors) in this list. Optional; a list may hold publications, users, or both.
   */
  users?: l.DidString[]

  /**
   * When the list was created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A named, ordered, shareable list of publications (like a Bluesky user list, but for site.standard.publication subscriptions). Lists are one level deep; a publication may appear in multiple lists. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string({ maxLength: 640, maxGraphemes: 64 }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 3000, maxGraphemes: 300 }),
    ),
    publications: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
      { maxLength: 500 },
    ),
    users: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'did' }), {
        maxLength: 500,
      }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
