/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex-schema'
import * as StandardReaderDefs from './defs.defs.js'

const $nsid = 'app.standard-reader.resolveUrl'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  url: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'uri' })),
  urls: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'uri' })),
  ),
  did: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'did' })),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.payload(
  'application/json',
  /*#__PURE__*/ l.typedUnion(
    [
      /*#__PURE__*/ l.typedRef<StandardReaderDefs.ResolveViewArticle>(
        (() => StandardReaderDefs.resolveViewArticle) as any,
      ),
      /*#__PURE__*/ l.typedRef<StandardReaderDefs.ResolveViewPublication>(
        (() => StandardReaderDefs.resolveViewPublication) as any,
      ),
      /*#__PURE__*/ l.typedRef<StandardReaderDefs.ResolveViewReaderLink>(
        (() => StandardReaderDefs.resolveViewReaderLink) as any,
      ),
      /*#__PURE__*/ l.typedRef<StandardReaderDefs.ResolveViewUnknown>(
        (() => StandardReaderDefs.resolveViewUnknown) as any,
      ),
    ],
    false,
  ),
)

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Match a web page URL to an indexed standard.site article or publication. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
