/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsHeaderLayoutRouteImport } from './routes/_docs-header-layout'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutAboutRouteImport } from './routes/_layout.about'
import { Route as LayoutCollectionsRouteImport } from './routes/_layout.collections'
import { Route as LayoutDiscoverRouteImport } from './routes/_layout.discover'
import { Route as LayoutFriendsRouteImport } from './routes/_layout.friends'
import { Route as LayoutHistoryRouteImport } from './routes/_layout.history'
import { Route as LayoutLatestRouteImport } from './routes/_layout.latest'
import { Route as LayoutLikesRouteImport } from './routes/_layout.likes'
import { Route as LayoutPrivacyRouteImport } from './routes/_layout.privacy'
import { Route as LayoutRecommendedRouteImport } from './routes/_layout.recommended'
import { Route as LayoutSavedRouteImport } from './routes/_layout.saved'
import { Route as LayoutSearchRouteImport } from './routes/_layout.search'
import { Route as LayoutTermsRouteImport } from './routes/_layout.terms'
import { Route as DevDigestRouteImport } from './routes/dev.digest'
import { Route as DevRtlRouteImport } from './routes/dev.rtl'
import { Route as DevWelcomeEmailRouteImport } from './routes/dev.welcome-email'
import { Route as ExtensionConnectedRouteImport } from './routes/extension.connected'
import { Route as ReviewThanksRouteImport } from './routes/review.thanks'
import { Route as XrpcSplatRouteImport } from './routes/xrpc/$'
import { Route as DocsHeaderLayoutDocsApiRouteImport } from './routes/_docs-header-layout.docs.api'
import { Route as DocsHeaderLayoutDocsIntroductionRouteImport } from './routes/_docs-header-layout.docs.introduction'
import { Route as DocsHeaderLayoutDocsLexiconsRouteImport } from './routes/_docs-header-layout.docs.lexicons'
import { Route as DocsHeaderLayoutDocsPublishingRouteImport } from './routes/_docs-header-layout.docs.publishing'
import { Route as DocsHeaderLayoutDocsRenderersRouteImport } from './routes/_docs-header-layout.docs.renderers'
import { Route as LayoutCollectionsIndexRouteImport } from './routes/_layout.collections.index'
import { Route as LayoutCollectionsNewRouteImport } from './routes/_layout.collections.new'
import { Route as LayoutFeedbackIndexRouteImport } from './routes/_layout.feedback.index'
import { Route as LayoutFeedbackReturnRouteImport } from './routes/_layout.feedback.return'
import { Route as LayoutLabelersIndexRouteImport } from './routes/_layout.labelers.index'
import { Route as LayoutLabelersDidRouteImport } from './routes/_layout.labelers.$did'
import { Route as LayoutPrivacyExtensionRouteImport } from './routes/_layout.privacy.extension'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout.settings.index'
import { Route as LayoutTagTagRouteImport } from './routes/_layout.tag.$tag'
import { Route as LayoutUDidRouteImport } from './routes/_layout.u.$did'
import { Route as ApiBskyPostRouteImport } from './routes/api/bsky/post'
import { Route as ApiDevDigestPreviewRouteImport } from './routes/api/dev/digest-preview'
import { Route as ApiDevWelcomePreviewRouteImport } from './routes/api/dev/welcome-preview'
import { Route as ApiDigestPreviewRouteImport } from './routes/api/digest/preview'
import { Route as ApiDigestUnsubscribeRouteImport } from './routes/api/digest/unsubscribe'
import { Route as ApiExtensionBookmarkRouteImport } from './routes/api/extension/bookmark'
import { Route as ApiExtensionDiscussionRouteImport } from './routes/api/extension/discussion'
import { Route as ApiExtensionFollowRouteImport } from './routes/api/extension/follow'
import { Route as ApiExtensionNarrationRouteImport } from './routes/api/extension/narration'
import { Route as ApiExtensionRecommendRouteImport } from './routes/api/extension/recommend'
import { Route as ApiExtensionResolveRouteImport } from './routes/api/extension/resolve'
import { Route as ApiExtensionSessionRouteImport } from './routes/api/extension/session'
import { Route as ApiOgArticleRouteImport } from './routes/api/og/article'
import { Route as ApiOgCollectionRouteImport } from './routes/api/og/collection'
import { Route as ApiOgListRouteImport } from './routes/api/og/list'
import { Route as ApiOgProfileRouteImport } from './routes/api/og/profile'
import { Route as ApiOgPublicationRouteImport } from './routes/api/og/publication'
import { Route as ApiOgQuoteRouteImport } from './routes/api/og/quote'
import { Route as ApiOgSiteRouteImport } from './routes/api/og/site'
import { Route as CollectionDidRkeyRouteImport } from './routes/collection.$did.$rkey'
import { Route as FeedLatestDidRouteImport } from './routes/feed.latest.$did'
import { Route as FeedTagTagRouteImport } from './routes/feed.tag.$tag'
import { Route as FeedUDidRouteImport } from './routes/feed.u.$did'
import { Route as SubscribeLoginDidRkeyRouteImport } from './routes/subscribe-login.$did.$rkey'
import { Route as SubscribeDidRkeyRouteImport } from './routes/subscribe.$did.$rkey'
import { Route as LayoutADidRkeyRouteImport } from './routes/_layout.a.$did.$rkey'
import { Route as LayoutCollectionsEditRkeyRouteImport } from './routes/_layout.collections.edit.$rkey'
import { Route as LayoutLDidRkeyRouteImport } from './routes/_layout.l.$did.$rkey'
import { Route as LayoutPDidRkeyRouteImport } from './routes/_layout.p.$did.$rkey'
import { Route as ApiAuthAtprotoAuthorizeRouteImport } from './routes/api/auth/atproto/authorize'
import { Route as ApiAuthAtprotoCallbackRouteImport } from './routes/api/auth/atproto/callback'
import { Route as ApiAuthAtprotoJwksDotjsonRouteImport } from './routes/api/auth/atproto/jwks[.]json'
import { Route as ApiAuthAtprotoMetadataDotjsonRouteImport } from './routes/api/auth/atproto/metadata[.]json'
import { Route as ApiAuthAtprotoSignupRouteImport } from './routes/api/auth/atproto/signup'
import { Route as ApiOgPageSlugRouteImport } from './routes/api/og/page.$slug'
import { Route as EmbedSubscribeDidRkeyRouteImport } from './routes/embed.subscribe.$did.$rkey'
import { Route as FeedCollectionDidRkeyRouteImport } from './routes/feed.collection.$did.$rkey'
import { Route as FeedLDidRkeyRouteImport } from './routes/feed.l.$did.$rkey'
import { Route as FeedPDidRkeyRouteImport } from './routes/feed.p.$did.$rkey'
import { Route as ApiAuthAtprotoReviewCallbackRouteImport } from './routes/api/auth/atproto/review/callback'
import { Route as ApiAuthAtprotoReviewMetadataDotjsonRouteImport } from './routes/api/auth/atproto/review/metadata[.]json'

const DocsHeaderLayoutRoute = DocsHeaderLayoutRouteImport.update({
  id: '/_docs-header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCollectionsRoute = LayoutCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDiscoverRoute = LayoutDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFriendsRoute = LayoutFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLatestRoute = LayoutLatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLikesRoute = LayoutLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrivacyRoute = LayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecommendedRoute = LayoutRecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSavedRoute = LayoutSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTermsRoute = LayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LayoutRoute,
} as any)
const DevDigestRoute = DevDigestRouteImport.update({
  id: '/dev/digest',
  path: '/dev/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRtlRoute = DevRtlRouteImport.update({
  id: '/dev/rtl',
  path: '/dev/rtl',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWelcomeEmailRoute = DevWelcomeEmailRouteImport.update({
  id: '/dev/welcome-email',
  path: '/dev/welcome-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionConnectedRoute = ExtensionConnectedRouteImport.update({
  id: '/extension/connected',
  path: '/extension/connected',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewThanksRoute = ReviewThanksRouteImport.update({
  id: '/review/thanks',
  path: '/review/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const XrpcSplatRoute = XrpcSplatRouteImport.update({
  id: '/xrpc/$',
  path: '/xrpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHeaderLayoutDocsApiRoute = DocsHeaderLayoutDocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => DocsHeaderLayoutRoute,
} as any)
const DocsHeaderLayoutDocsIntroductionRoute =
  DocsHeaderLayoutDocsIntroductionRouteImport.update({
    id: '/docs/introduction',
    path: '/docs/introduction',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const DocsHeaderLayoutDocsLexiconsRoute =
  DocsHeaderLayoutDocsLexiconsRouteImport.update({
    id: '/docs/lexicons',
    path: '/docs/lexicons',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const DocsHeaderLayoutDocsPublishingRoute =
  DocsHeaderLayoutDocsPublishingRouteImport.update({
    id: '/docs/publishing',
    path: '/docs/publishing',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const DocsHeaderLayoutDocsRenderersRoute =
  DocsHeaderLayoutDocsRenderersRouteImport.update({
    id: '/docs/renderers',
    path: '/docs/renderers',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const LayoutCollectionsIndexRoute = LayoutCollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCollectionsRoute,
} as any)
const LayoutCollectionsNewRoute = LayoutCollectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutCollectionsRoute,
} as any)
const LayoutFeedbackIndexRoute = LayoutFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeedbackReturnRoute = LayoutFeedbackReturnRouteImport.update({
  id: '/feedback/return',
  path: '/feedback/return',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLabelersIndexRoute = LayoutLabelersIndexRouteImport.update({
  id: '/labelers/',
  path: '/labelers/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLabelersDidRoute = LayoutLabelersDidRouteImport.update({
  id: '/labelers/$did',
  path: '/labelers/$did',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrivacyExtensionRoute = LayoutPrivacyExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => LayoutPrivacyRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTagTagRoute = LayoutTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUDidRoute = LayoutUDidRouteImport.update({
  id: '/u/$did',
  path: '/u/$did',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiBskyPostRoute = ApiBskyPostRouteImport.update({
  id: '/api/bsky/post',
  path: '/api/bsky/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevDigestPreviewRoute = ApiDevDigestPreviewRouteImport.update({
  id: '/api/dev/digest-preview',
  path: '/api/dev/digest-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevWelcomePreviewRoute = ApiDevWelcomePreviewRouteImport.update({
  id: '/api/dev/welcome-preview',
  path: '/api/dev/welcome-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestPreviewRoute = ApiDigestPreviewRouteImport.update({
  id: '/api/digest/preview',
  path: '/api/digest/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestUnsubscribeRoute = ApiDigestUnsubscribeRouteImport.update({
  id: '/api/digest/unsubscribe',
  path: '/api/digest/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionBookmarkRoute = ApiExtensionBookmarkRouteImport.update({
  id: '/api/extension/bookmark',
  path: '/api/extension/bookmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionDiscussionRoute = ApiExtensionDiscussionRouteImport.update({
  id: '/api/extension/discussion',
  path: '/api/extension/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionFollowRoute = ApiExtensionFollowRouteImport.update({
  id: '/api/extension/follow',
  path: '/api/extension/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionNarrationRoute = ApiExtensionNarrationRouteImport.update({
  id: '/api/extension/narration',
  path: '/api/extension/narration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionRecommendRoute = ApiExtensionRecommendRouteImport.update({
  id: '/api/extension/recommend',
  path: '/api/extension/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionResolveRoute = ApiExtensionResolveRouteImport.update({
  id: '/api/extension/resolve',
  path: '/api/extension/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionSessionRoute = ApiExtensionSessionRouteImport.update({
  id: '/api/extension/session',
  path: '/api/extension/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgArticleRoute = ApiOgArticleRouteImport.update({
  id: '/api/og/article',
  path: '/api/og/article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCollectionRoute = ApiOgCollectionRouteImport.update({
  id: '/api/og/collection',
  path: '/api/og/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgListRoute = ApiOgListRouteImport.update({
  id: '/api/og/list',
  path: '/api/og/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgProfileRoute = ApiOgProfileRouteImport.update({
  id: '/api/og/profile',
  path: '/api/og/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPublicationRoute = ApiOgPublicationRouteImport.update({
  id: '/api/og/publication',
  path: '/api/og/publication',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgQuoteRoute = ApiOgQuoteRouteImport.update({
  id: '/api/og/quote',
  path: '/api/og/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSiteRoute = ApiOgSiteRouteImport.update({
  id: '/api/og/site',
  path: '/api/og/site',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionDidRkeyRoute = CollectionDidRkeyRouteImport.update({
  id: '/collection/$did/$rkey',
  path: '/collection/$did/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedLatestDidRoute = FeedLatestDidRouteImport.update({
  id: '/feed/latest/$did',
  path: '/feed/latest/$did',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedTagTagRoute = FeedTagTagRouteImport.update({
  id: '/feed/tag/$tag',
  path: '/feed/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedUDidRoute = FeedUDidRouteImport.update({
  id: '/feed/u/$did',
  path: '/feed/u/$did',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeLoginDidRkeyRoute = SubscribeLoginDidRkeyRouteImport.update({
  id: '/subscribe-login/$did/$rkey',
  path: '/subscribe-login/$did/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeDidRkeyRoute = SubscribeDidRkeyRouteImport.update({
  id: '/subscribe/$did/$rkey',
  path: '/subscribe/$did/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutADidRkeyRoute = LayoutADidRkeyRouteImport.update({
  id: '/a/$did/$rkey',
  path: '/a/$did/$rkey',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCollectionsEditRkeyRoute =
  LayoutCollectionsEditRkeyRouteImport.update({
    id: '/edit/$rkey',
    path: '/edit/$rkey',
    getParentRoute: () => LayoutCollectionsRoute,
  } as any)
const LayoutLDidRkeyRoute = LayoutLDidRkeyRouteImport.update({
  id: '/l/$did/$rkey',
  path: '/l/$did/$rkey',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPDidRkeyRoute = LayoutPDidRkeyRouteImport.update({
  id: '/p/$did/$rkey',
  path: '/p/$did/$rkey',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAuthAtprotoAuthorizeRoute = ApiAuthAtprotoAuthorizeRouteImport.update({
  id: '/api/auth/atproto/authorize',
  path: '/api/auth/atproto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoCallbackRoute = ApiAuthAtprotoCallbackRouteImport.update({
  id: '/api/auth/atproto/callback',
  path: '/api/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoJwksDotjsonRoute =
  ApiAuthAtprotoJwksDotjsonRouteImport.update({
    id: '/api/auth/atproto/jwks.json',
    path: '/api/auth/atproto/jwks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoMetadataDotjsonRoute =
  ApiAuthAtprotoMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/metadata.json',
    path: '/api/auth/atproto/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoSignupRoute = ApiAuthAtprotoSignupRouteImport.update({
  id: '/api/auth/atproto/signup',
  path: '/api/auth/atproto/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPageSlugRoute = ApiOgPageSlugRouteImport.update({
  id: '/api/og/page/$slug',
  path: '/api/og/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSubscribeDidRkeyRoute = EmbedSubscribeDidRkeyRouteImport.update({
  id: '/embed/subscribe/$did/$rkey',
  path: '/embed/subscribe/$did/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedCollectionDidRkeyRoute = FeedCollectionDidRkeyRouteImport.update({
  id: '/feed/collection/$did/$rkey',
  path: '/feed/collection/$did/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedLDidRkeyRoute = FeedLDidRkeyRouteImport.update({
  id: '/feed/l/$did/$rkey',
  path: '/feed/l/$did/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPDidRkeyRoute = FeedPDidRkeyRouteImport.update({
  id: '/feed/p/$did/$rkey',
  path: '/feed/p/$did/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoReviewCallbackRoute =
  ApiAuthAtprotoReviewCallbackRouteImport.update({
    id: '/api/auth/atproto/review/callback',
    path: '/api/auth/atproto/review/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoReviewMetadataDotjsonRoute =
  ApiAuthAtprotoReviewMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/review/metadata.json',
    path: '/api/auth/atproto/review/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof LayoutAboutRoute
  '/collections': typeof LayoutCollectionsRouteWithChildren
  '/discover': typeof LayoutDiscoverRoute
  '/friends': typeof LayoutFriendsRoute
  '/history': typeof LayoutHistoryRoute
  '/latest': typeof LayoutLatestRoute
  '/likes': typeof LayoutLikesRoute
  '/privacy': typeof LayoutPrivacyRouteWithChildren
  '/recommended': typeof LayoutRecommendedRoute
  '/saved': typeof LayoutSavedRoute
  '/search': typeof LayoutSearchRoute
  '/terms': typeof LayoutTermsRoute
  '/dev/digest': typeof DevDigestRoute
  '/dev/rtl': typeof DevRtlRoute
  '/dev/welcome-email': typeof DevWelcomeEmailRoute
  '/extension/connected': typeof ExtensionConnectedRoute
  '/review/thanks': typeof ReviewThanksRoute
  '/xrpc/$': typeof XrpcSplatRoute
  '/docs/api': typeof DocsHeaderLayoutDocsApiRoute
  '/docs/introduction': typeof DocsHeaderLayoutDocsIntroductionRoute
  '/docs/lexicons': typeof DocsHeaderLayoutDocsLexiconsRoute
  '/docs/publishing': typeof DocsHeaderLayoutDocsPublishingRoute
  '/docs/renderers': typeof DocsHeaderLayoutDocsRenderersRoute
  '/collections/new': typeof LayoutCollectionsNewRoute
  '/feedback/return': typeof LayoutFeedbackReturnRoute
  '/labelers/$did': typeof LayoutLabelersDidRoute
  '/privacy/extension': typeof LayoutPrivacyExtensionRoute
  '/tag/$tag': typeof LayoutTagTagRoute
  '/u/$did': typeof LayoutUDidRoute
  '/api/bsky/post': typeof ApiBskyPostRoute
  '/api/dev/digest-preview': typeof ApiDevDigestPreviewRoute
  '/api/dev/welcome-preview': typeof ApiDevWelcomePreviewRoute
  '/api/digest/preview': typeof ApiDigestPreviewRoute
  '/api/digest/unsubscribe': typeof ApiDigestUnsubscribeRoute
  '/api/extension/bookmark': typeof ApiExtensionBookmarkRoute
  '/api/extension/discussion': typeof ApiExtensionDiscussionRoute
  '/api/extension/follow': typeof ApiExtensionFollowRoute
  '/api/extension/narration': typeof ApiExtensionNarrationRoute
  '/api/extension/recommend': typeof ApiExtensionRecommendRoute
  '/api/extension/resolve': typeof ApiExtensionResolveRoute
  '/api/extension/session': typeof ApiExtensionSessionRoute
  '/api/og/article': typeof ApiOgArticleRoute
  '/api/og/collection': typeof ApiOgCollectionRoute
  '/api/og/list': typeof ApiOgListRoute
  '/api/og/profile': typeof ApiOgProfileRoute
  '/api/og/publication': typeof ApiOgPublicationRoute
  '/api/og/quote': typeof ApiOgQuoteRoute
  '/api/og/site': typeof ApiOgSiteRoute
  '/collection/$did/$rkey': typeof CollectionDidRkeyRoute
  '/feed/latest/$did': typeof FeedLatestDidRoute
  '/feed/tag/$tag': typeof FeedTagTagRoute
  '/feed/u/$did': typeof FeedUDidRoute
  '/subscribe-login/$did/$rkey': typeof SubscribeLoginDidRkeyRoute
  '/subscribe/$did/$rkey': typeof SubscribeDidRkeyRoute
  '/collections/': typeof LayoutCollectionsIndexRoute
  '/feedback/': typeof LayoutFeedbackIndexRoute
  '/labelers/': typeof LayoutLabelersIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/a/$did/$rkey': typeof LayoutADidRkeyRoute
  '/collections/edit/$rkey': typeof LayoutCollectionsEditRkeyRoute
  '/l/$did/$rkey': typeof LayoutLDidRkeyRoute
  '/p/$did/$rkey': typeof LayoutPDidRkeyRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
  '/embed/subscribe/$did/$rkey': typeof EmbedSubscribeDidRkeyRoute
  '/feed/collection/$did/$rkey': typeof FeedCollectionDidRkeyRoute
  '/feed/l/$did/$rkey': typeof FeedLDidRkeyRoute
  '/feed/p/$did/$rkey': typeof FeedPDidRkeyRoute
  '/api/auth/atproto/review/callback': typeof ApiAuthAtprotoReviewCallbackRoute
  '/api/auth/atproto/review/metadata.json': typeof ApiAuthAtprotoReviewMetadataDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof LayoutAboutRoute
  '/discover': typeof LayoutDiscoverRoute
  '/friends': typeof LayoutFriendsRoute
  '/history': typeof LayoutHistoryRoute
  '/latest': typeof LayoutLatestRoute
  '/likes': typeof LayoutLikesRoute
  '/privacy': typeof LayoutPrivacyRouteWithChildren
  '/recommended': typeof LayoutRecommendedRoute
  '/saved': typeof LayoutSavedRoute
  '/search': typeof LayoutSearchRoute
  '/terms': typeof LayoutTermsRoute
  '/dev/digest': typeof DevDigestRoute
  '/dev/rtl': typeof DevRtlRoute
  '/dev/welcome-email': typeof DevWelcomeEmailRoute
  '/extension/connected': typeof ExtensionConnectedRoute
  '/review/thanks': typeof ReviewThanksRoute
  '/xrpc/$': typeof XrpcSplatRoute
  '/docs/api': typeof DocsHeaderLayoutDocsApiRoute
  '/docs/introduction': typeof DocsHeaderLayoutDocsIntroductionRoute
  '/docs/lexicons': typeof DocsHeaderLayoutDocsLexiconsRoute
  '/docs/publishing': typeof DocsHeaderLayoutDocsPublishingRoute
  '/docs/renderers': typeof DocsHeaderLayoutDocsRenderersRoute
  '/collections/new': typeof LayoutCollectionsNewRoute
  '/feedback/return': typeof LayoutFeedbackReturnRoute
  '/labelers/$did': typeof LayoutLabelersDidRoute
  '/privacy/extension': typeof LayoutPrivacyExtensionRoute
  '/tag/$tag': typeof LayoutTagTagRoute
  '/u/$did': typeof LayoutUDidRoute
  '/api/bsky/post': typeof ApiBskyPostRoute
  '/api/dev/digest-preview': typeof ApiDevDigestPreviewRoute
  '/api/dev/welcome-preview': typeof ApiDevWelcomePreviewRoute
  '/api/digest/preview': typeof ApiDigestPreviewRoute
  '/api/digest/unsubscribe': typeof ApiDigestUnsubscribeRoute
  '/api/extension/bookmark': typeof ApiExtensionBookmarkRoute
  '/api/extension/discussion': typeof ApiExtensionDiscussionRoute
  '/api/extension/follow': typeof ApiExtensionFollowRoute
  '/api/extension/narration': typeof ApiExtensionNarrationRoute
  '/api/extension/recommend': typeof ApiExtensionRecommendRoute
  '/api/extension/resolve': typeof ApiExtensionResolveRoute
  '/api/extension/session': typeof ApiExtensionSessionRoute
  '/api/og/article': typeof ApiOgArticleRoute
  '/api/og/collection': typeof ApiOgCollectionRoute
  '/api/og/list': typeof ApiOgListRoute
  '/api/og/profile': typeof ApiOgProfileRoute
  '/api/og/publication': typeof ApiOgPublicationRoute
  '/api/og/quote': typeof ApiOgQuoteRoute
  '/api/og/site': typeof ApiOgSiteRoute
  '/collection/$did/$rkey': typeof CollectionDidRkeyRoute
  '/feed/latest/$did': typeof FeedLatestDidRoute
  '/feed/tag/$tag': typeof FeedTagTagRoute
  '/feed/u/$did': typeof FeedUDidRoute
  '/subscribe-login/$did/$rkey': typeof SubscribeLoginDidRkeyRoute
  '/subscribe/$did/$rkey': typeof SubscribeDidRkeyRoute
  '/collections': typeof LayoutCollectionsIndexRoute
  '/feedback': typeof LayoutFeedbackIndexRoute
  '/labelers': typeof LayoutLabelersIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/a/$did/$rkey': typeof LayoutADidRkeyRoute
  '/collections/edit/$rkey': typeof LayoutCollectionsEditRkeyRoute
  '/l/$did/$rkey': typeof LayoutLDidRkeyRoute
  '/p/$did/$rkey': typeof LayoutPDidRkeyRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
  '/embed/subscribe/$did/$rkey': typeof EmbedSubscribeDidRkeyRoute
  '/feed/collection/$did/$rkey': typeof FeedCollectionDidRkeyRoute
  '/feed/l/$did/$rkey': typeof FeedLDidRkeyRoute
  '/feed/p/$did/$rkey': typeof FeedPDidRkeyRoute
  '/api/auth/atproto/review/callback': typeof ApiAuthAtprotoReviewCallbackRoute
  '/api/auth/atproto/review/metadata.json': typeof ApiAuthAtprotoReviewMetadataDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_docs-header-layout': typeof DocsHeaderLayoutRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/collections': typeof LayoutCollectionsRouteWithChildren
  '/_layout/discover': typeof LayoutDiscoverRoute
  '/_layout/friends': typeof LayoutFriendsRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/latest': typeof LayoutLatestRoute
  '/_layout/likes': typeof LayoutLikesRoute
  '/_layout/privacy': typeof LayoutPrivacyRouteWithChildren
  '/_layout/recommended': typeof LayoutRecommendedRoute
  '/_layout/saved': typeof LayoutSavedRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/terms': typeof LayoutTermsRoute
  '/dev/digest': typeof DevDigestRoute
  '/dev/rtl': typeof DevRtlRoute
  '/dev/welcome-email': typeof DevWelcomeEmailRoute
  '/extension/connected': typeof ExtensionConnectedRoute
  '/review/thanks': typeof ReviewThanksRoute
  '/xrpc/$': typeof XrpcSplatRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_docs-header-layout/docs/api': typeof DocsHeaderLayoutDocsApiRoute
  '/_docs-header-layout/docs/introduction': typeof DocsHeaderLayoutDocsIntroductionRoute
  '/_docs-header-layout/docs/lexicons': typeof DocsHeaderLayoutDocsLexiconsRoute
  '/_docs-header-layout/docs/publishing': typeof DocsHeaderLayoutDocsPublishingRoute
  '/_docs-header-layout/docs/renderers': typeof DocsHeaderLayoutDocsRenderersRoute
  '/_layout/collections/new': typeof LayoutCollectionsNewRoute
  '/_layout/feedback/return': typeof LayoutFeedbackReturnRoute
  '/_layout/labelers/$did': typeof LayoutLabelersDidRoute
  '/_layout/privacy/extension': typeof LayoutPrivacyExtensionRoute
  '/_layout/tag/$tag': typeof LayoutTagTagRoute
  '/_layout/u/$did': typeof LayoutUDidRoute
  '/api/bsky/post': typeof ApiBskyPostRoute
  '/api/dev/digest-preview': typeof ApiDevDigestPreviewRoute
  '/api/dev/welcome-preview': typeof ApiDevWelcomePreviewRoute
  '/api/digest/preview': typeof ApiDigestPreviewRoute
  '/api/digest/unsubscribe': typeof ApiDigestUnsubscribeRoute
  '/api/extension/bookmark': typeof ApiExtensionBookmarkRoute
  '/api/extension/discussion': typeof ApiExtensionDiscussionRoute
  '/api/extension/follow': typeof ApiExtensionFollowRoute
  '/api/extension/narration': typeof ApiExtensionNarrationRoute
  '/api/extension/recommend': typeof ApiExtensionRecommendRoute
  '/api/extension/resolve': typeof ApiExtensionResolveRoute
  '/api/extension/session': typeof ApiExtensionSessionRoute
  '/api/og/article': typeof ApiOgArticleRoute
  '/api/og/collection': typeof ApiOgCollectionRoute
  '/api/og/list': typeof ApiOgListRoute
  '/api/og/profile': typeof ApiOgProfileRoute
  '/api/og/publication': typeof ApiOgPublicationRoute
  '/api/og/quote': typeof ApiOgQuoteRoute
  '/api/og/site': typeof ApiOgSiteRoute
  '/collection/$did/$rkey': typeof CollectionDidRkeyRoute
  '/feed/latest/$did': typeof FeedLatestDidRoute
  '/feed/tag/$tag': typeof FeedTagTagRoute
  '/feed/u/$did': typeof FeedUDidRoute
  '/subscribe-login/$did/$rkey': typeof SubscribeLoginDidRkeyRoute
  '/subscribe/$did/$rkey': typeof SubscribeDidRkeyRoute
  '/_layout/collections/': typeof LayoutCollectionsIndexRoute
  '/_layout/feedback/': typeof LayoutFeedbackIndexRoute
  '/_layout/labelers/': typeof LayoutLabelersIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/a/$did/$rkey': typeof LayoutADidRkeyRoute
  '/_layout/collections/edit/$rkey': typeof LayoutCollectionsEditRkeyRoute
  '/_layout/l/$did/$rkey': typeof LayoutLDidRkeyRoute
  '/_layout/p/$did/$rkey': typeof LayoutPDidRkeyRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
  '/embed/subscribe/$did/$rkey': typeof EmbedSubscribeDidRkeyRoute
  '/feed/collection/$did/$rkey': typeof FeedCollectionDidRkeyRoute
  '/feed/l/$did/$rkey': typeof FeedLDidRkeyRoute
  '/feed/p/$did/$rkey': typeof FeedPDidRkeyRoute
  '/api/auth/atproto/review/callback': typeof ApiAuthAtprotoReviewCallbackRoute
  '/api/auth/atproto/review/metadata.json': typeof ApiAuthAtprotoReviewMetadataDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/welcome'
    | '/about'
    | '/collections'
    | '/discover'
    | '/friends'
    | '/history'
    | '/latest'
    | '/likes'
    | '/privacy'
    | '/recommended'
    | '/saved'
    | '/search'
    | '/terms'
    | '/dev/digest'
    | '/dev/rtl'
    | '/dev/welcome-email'
    | '/extension/connected'
    | '/review/thanks'
    | '/xrpc/$'
    | '/docs/api'
    | '/docs/introduction'
    | '/docs/lexicons'
    | '/docs/publishing'
    | '/docs/renderers'
    | '/collections/new'
    | '/feedback/return'
    | '/labelers/$did'
    | '/privacy/extension'
    | '/tag/$tag'
    | '/u/$did'
    | '/api/bsky/post'
    | '/api/dev/digest-preview'
    | '/api/dev/welcome-preview'
    | '/api/digest/preview'
    | '/api/digest/unsubscribe'
    | '/api/extension/bookmark'
    | '/api/extension/discussion'
    | '/api/extension/follow'
    | '/api/extension/narration'
    | '/api/extension/recommend'
    | '/api/extension/resolve'
    | '/api/extension/session'
    | '/api/og/article'
    | '/api/og/collection'
    | '/api/og/list'
    | '/api/og/profile'
    | '/api/og/publication'
    | '/api/og/quote'
    | '/api/og/site'
    | '/collection/$did/$rkey'
    | '/feed/latest/$did'
    | '/feed/tag/$tag'
    | '/feed/u/$did'
    | '/subscribe-login/$did/$rkey'
    | '/subscribe/$did/$rkey'
    | '/collections/'
    | '/feedback/'
    | '/labelers/'
    | '/settings/'
    | '/a/$did/$rkey'
    | '/collections/edit/$rkey'
    | '/l/$did/$rkey'
    | '/p/$did/$rkey'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/api/og/page/$slug'
    | '/embed/subscribe/$did/$rkey'
    | '/feed/collection/$did/$rkey'
    | '/feed/l/$did/$rkey'
    | '/feed/p/$did/$rkey'
    | '/api/auth/atproto/review/callback'
    | '/api/auth/atproto/review/metadata.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/welcome'
    | '/about'
    | '/discover'
    | '/friends'
    | '/history'
    | '/latest'
    | '/likes'
    | '/privacy'
    | '/recommended'
    | '/saved'
    | '/search'
    | '/terms'
    | '/dev/digest'
    | '/dev/rtl'
    | '/dev/welcome-email'
    | '/extension/connected'
    | '/review/thanks'
    | '/xrpc/$'
    | '/docs/api'
    | '/docs/introduction'
    | '/docs/lexicons'
    | '/docs/publishing'
    | '/docs/renderers'
    | '/collections/new'
    | '/feedback/return'
    | '/labelers/$did'
    | '/privacy/extension'
    | '/tag/$tag'
    | '/u/$did'
    | '/api/bsky/post'
    | '/api/dev/digest-preview'
    | '/api/dev/welcome-preview'
    | '/api/digest/preview'
    | '/api/digest/unsubscribe'
    | '/api/extension/bookmark'
    | '/api/extension/discussion'
    | '/api/extension/follow'
    | '/api/extension/narration'
    | '/api/extension/recommend'
    | '/api/extension/resolve'
    | '/api/extension/session'
    | '/api/og/article'
    | '/api/og/collection'
    | '/api/og/list'
    | '/api/og/profile'
    | '/api/og/publication'
    | '/api/og/quote'
    | '/api/og/site'
    | '/collection/$did/$rkey'
    | '/feed/latest/$did'
    | '/feed/tag/$tag'
    | '/feed/u/$did'
    | '/subscribe-login/$did/$rkey'
    | '/subscribe/$did/$rkey'
    | '/collections'
    | '/feedback'
    | '/labelers'
    | '/settings'
    | '/a/$did/$rkey'
    | '/collections/edit/$rkey'
    | '/l/$did/$rkey'
    | '/p/$did/$rkey'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/api/og/page/$slug'
    | '/embed/subscribe/$did/$rkey'
    | '/feed/collection/$did/$rkey'
    | '/feed/l/$did/$rkey'
    | '/feed/p/$did/$rkey'
    | '/api/auth/atproto/review/callback'
    | '/api/auth/atproto/review/metadata.json'
  id:
    | '__root__'
    | '/_docs-header-layout'
    | '/_layout'
    | '/login'
    | '/welcome'
    | '/_layout/about'
    | '/_layout/collections'
    | '/_layout/discover'
    | '/_layout/friends'
    | '/_layout/history'
    | '/_layout/latest'
    | '/_layout/likes'
    | '/_layout/privacy'
    | '/_layout/recommended'
    | '/_layout/saved'
    | '/_layout/search'
    | '/_layout/terms'
    | '/dev/digest'
    | '/dev/rtl'
    | '/dev/welcome-email'
    | '/extension/connected'
    | '/review/thanks'
    | '/xrpc/$'
    | '/_layout/'
    | '/_docs-header-layout/docs/api'
    | '/_docs-header-layout/docs/introduction'
    | '/_docs-header-layout/docs/lexicons'
    | '/_docs-header-layout/docs/publishing'
    | '/_docs-header-layout/docs/renderers'
    | '/_layout/collections/new'
    | '/_layout/feedback/return'
    | '/_layout/labelers/$did'
    | '/_layout/privacy/extension'
    | '/_layout/tag/$tag'
    | '/_layout/u/$did'
    | '/api/bsky/post'
    | '/api/dev/digest-preview'
    | '/api/dev/welcome-preview'
    | '/api/digest/preview'
    | '/api/digest/unsubscribe'
    | '/api/extension/bookmark'
    | '/api/extension/discussion'
    | '/api/extension/follow'
    | '/api/extension/narration'
    | '/api/extension/recommend'
    | '/api/extension/resolve'
    | '/api/extension/session'
    | '/api/og/article'
    | '/api/og/collection'
    | '/api/og/list'
    | '/api/og/profile'
    | '/api/og/publication'
    | '/api/og/quote'
    | '/api/og/site'
    | '/collection/$did/$rkey'
    | '/feed/latest/$did'
    | '/feed/tag/$tag'
    | '/feed/u/$did'
    | '/subscribe-login/$did/$rkey'
    | '/subscribe/$did/$rkey'
    | '/_layout/collections/'
    | '/_layout/feedback/'
    | '/_layout/labelers/'
    | '/_layout/settings/'
    | '/_layout/a/$did/$rkey'
    | '/_layout/collections/edit/$rkey'
    | '/_layout/l/$did/$rkey'
    | '/_layout/p/$did/$rkey'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/api/og/page/$slug'
    | '/embed/subscribe/$did/$rkey'
    | '/feed/collection/$did/$rkey'
    | '/feed/l/$did/$rkey'
    | '/feed/p/$did/$rkey'
    | '/api/auth/atproto/review/callback'
    | '/api/auth/atproto/review/metadata.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsHeaderLayoutRoute: typeof DocsHeaderLayoutRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  DevDigestRoute: typeof DevDigestRoute
  DevRtlRoute: typeof DevRtlRoute
  DevWelcomeEmailRoute: typeof DevWelcomeEmailRoute
  ExtensionConnectedRoute: typeof ExtensionConnectedRoute
  ReviewThanksRoute: typeof ReviewThanksRoute
  XrpcSplatRoute: typeof XrpcSplatRoute
  ApiBskyPostRoute: typeof ApiBskyPostRoute
  ApiDevDigestPreviewRoute: typeof ApiDevDigestPreviewRoute
  ApiDevWelcomePreviewRoute: typeof ApiDevWelcomePreviewRoute
  ApiDigestPreviewRoute: typeof ApiDigestPreviewRoute
  ApiDigestUnsubscribeRoute: typeof ApiDigestUnsubscribeRoute
  ApiExtensionBookmarkRoute: typeof ApiExtensionBookmarkRoute
  ApiExtensionDiscussionRoute: typeof ApiExtensionDiscussionRoute
  ApiExtensionFollowRoute: typeof ApiExtensionFollowRoute
  ApiExtensionNarrationRoute: typeof ApiExtensionNarrationRoute
  ApiExtensionRecommendRoute: typeof ApiExtensionRecommendRoute
  ApiExtensionResolveRoute: typeof ApiExtensionResolveRoute
  ApiExtensionSessionRoute: typeof ApiExtensionSessionRoute
  ApiOgArticleRoute: typeof ApiOgArticleRoute
  ApiOgCollectionRoute: typeof ApiOgCollectionRoute
  ApiOgListRoute: typeof ApiOgListRoute
  ApiOgProfileRoute: typeof ApiOgProfileRoute
  ApiOgPublicationRoute: typeof ApiOgPublicationRoute
  ApiOgQuoteRoute: typeof ApiOgQuoteRoute
  ApiOgSiteRoute: typeof ApiOgSiteRoute
  CollectionDidRkeyRoute: typeof CollectionDidRkeyRoute
  FeedLatestDidRoute: typeof FeedLatestDidRoute
  FeedTagTagRoute: typeof FeedTagTagRoute
  FeedUDidRoute: typeof FeedUDidRoute
  SubscribeLoginDidRkeyRoute: typeof SubscribeLoginDidRkeyRoute
  SubscribeDidRkeyRoute: typeof SubscribeDidRkeyRoute
  ApiAuthAtprotoAuthorizeRoute: typeof ApiAuthAtprotoAuthorizeRoute
  ApiAuthAtprotoCallbackRoute: typeof ApiAuthAtprotoCallbackRoute
  ApiAuthAtprotoJwksDotjsonRoute: typeof ApiAuthAtprotoJwksDotjsonRoute
  ApiAuthAtprotoMetadataDotjsonRoute: typeof ApiAuthAtprotoMetadataDotjsonRoute
  ApiAuthAtprotoSignupRoute: typeof ApiAuthAtprotoSignupRoute
  ApiOgPageSlugRoute: typeof ApiOgPageSlugRoute
  EmbedSubscribeDidRkeyRoute: typeof EmbedSubscribeDidRkeyRoute
  FeedCollectionDidRkeyRoute: typeof FeedCollectionDidRkeyRoute
  FeedLDidRkeyRoute: typeof FeedLDidRkeyRoute
  FeedPDidRkeyRoute: typeof FeedPDidRkeyRoute
  ApiAuthAtprotoReviewCallbackRoute: typeof ApiAuthAtprotoReviewCallbackRoute
  ApiAuthAtprotoReviewMetadataDotjsonRoute: typeof ApiAuthAtprotoReviewMetadataDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs-header-layout': {
      id: '/_docs-header-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsHeaderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/collections': {
      id: '/_layout/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof LayoutCollectionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/discover': {
      id: '/_layout/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof LayoutDiscoverRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/friends': {
      id: '/_layout/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof LayoutFriendsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/latest': {
      id: '/_layout/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LayoutLatestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/likes': {
      id: '/_layout/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LayoutLikesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy': {
      id: '/_layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LayoutPrivacyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recommended': {
      id: '/_layout/recommended'
      path: '/recommended'
      fullPath: '/recommended'
      preLoaderRoute: typeof LayoutRecommendedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/saved': {
      id: '/_layout/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof LayoutSavedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/terms': {
      id: '/_layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LayoutTermsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/dev/digest': {
      id: '/dev/digest'
      path: '/dev/digest'
      fullPath: '/dev/digest'
      preLoaderRoute: typeof DevDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/rtl': {
      id: '/dev/rtl'
      path: '/dev/rtl'
      fullPath: '/dev/rtl'
      preLoaderRoute: typeof DevRtlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/welcome-email': {
      id: '/dev/welcome-email'
      path: '/dev/welcome-email'
      fullPath: '/dev/welcome-email'
      preLoaderRoute: typeof DevWelcomeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/connected': {
      id: '/extension/connected'
      path: '/extension/connected'
      fullPath: '/extension/connected'
      preLoaderRoute: typeof ExtensionConnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/thanks': {
      id: '/review/thanks'
      path: '/review/thanks'
      fullPath: '/review/thanks'
      preLoaderRoute: typeof ReviewThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/$': {
      id: '/xrpc/$'
      path: '/xrpc/$'
      fullPath: '/xrpc/$'
      preLoaderRoute: typeof XrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs-header-layout/docs/api': {
      id: '/_docs-header-layout/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsHeaderLayoutDocsApiRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/introduction': {
      id: '/_docs-header-layout/docs/introduction'
      path: '/docs/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof DocsHeaderLayoutDocsIntroductionRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/lexicons': {
      id: '/_docs-header-layout/docs/lexicons'
      path: '/docs/lexicons'
      fullPath: '/docs/lexicons'
      preLoaderRoute: typeof DocsHeaderLayoutDocsLexiconsRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/publishing': {
      id: '/_docs-header-layout/docs/publishing'
      path: '/docs/publishing'
      fullPath: '/docs/publishing'
      preLoaderRoute: typeof DocsHeaderLayoutDocsPublishingRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/renderers': {
      id: '/_docs-header-layout/docs/renderers'
      path: '/docs/renderers'
      fullPath: '/docs/renderers'
      preLoaderRoute: typeof DocsHeaderLayoutDocsRenderersRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_layout/collections/': {
      id: '/_layout/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof LayoutCollectionsIndexRouteImport
      parentRoute: typeof LayoutCollectionsRoute
    }
    '/_layout/collections/new': {
      id: '/_layout/collections/new'
      path: '/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof LayoutCollectionsNewRouteImport
      parentRoute: typeof LayoutCollectionsRoute
    }
    '/_layout/feedback/': {
      id: '/_layout/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof LayoutFeedbackIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/feedback/return': {
      id: '/_layout/feedback/return'
      path: '/feedback/return'
      fullPath: '/feedback/return'
      preLoaderRoute: typeof LayoutFeedbackReturnRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/labelers/': {
      id: '/_layout/labelers/'
      path: '/labelers'
      fullPath: '/labelers/'
      preLoaderRoute: typeof LayoutLabelersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/labelers/$did': {
      id: '/_layout/labelers/$did'
      path: '/labelers/$did'
      fullPath: '/labelers/$did'
      preLoaderRoute: typeof LayoutLabelersDidRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy/extension': {
      id: '/_layout/privacy/extension'
      path: '/extension'
      fullPath: '/privacy/extension'
      preLoaderRoute: typeof LayoutPrivacyExtensionRouteImport
      parentRoute: typeof LayoutPrivacyRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tag/$tag': {
      id: '/_layout/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof LayoutTagTagRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/u/$did': {
      id: '/_layout/u/$did'
      path: '/u/$did'
      fullPath: '/u/$did'
      preLoaderRoute: typeof LayoutUDidRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/bsky/post': {
      id: '/api/bsky/post'
      path: '/api/bsky/post'
      fullPath: '/api/bsky/post'
      preLoaderRoute: typeof ApiBskyPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/digest-preview': {
      id: '/api/dev/digest-preview'
      path: '/api/dev/digest-preview'
      fullPath: '/api/dev/digest-preview'
      preLoaderRoute: typeof ApiDevDigestPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/welcome-preview': {
      id: '/api/dev/welcome-preview'
      path: '/api/dev/welcome-preview'
      fullPath: '/api/dev/welcome-preview'
      preLoaderRoute: typeof ApiDevWelcomePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest/preview': {
      id: '/api/digest/preview'
      path: '/api/digest/preview'
      fullPath: '/api/digest/preview'
      preLoaderRoute: typeof ApiDigestPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest/unsubscribe': {
      id: '/api/digest/unsubscribe'
      path: '/api/digest/unsubscribe'
      fullPath: '/api/digest/unsubscribe'
      preLoaderRoute: typeof ApiDigestUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/bookmark': {
      id: '/api/extension/bookmark'
      path: '/api/extension/bookmark'
      fullPath: '/api/extension/bookmark'
      preLoaderRoute: typeof ApiExtensionBookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/discussion': {
      id: '/api/extension/discussion'
      path: '/api/extension/discussion'
      fullPath: '/api/extension/discussion'
      preLoaderRoute: typeof ApiExtensionDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/follow': {
      id: '/api/extension/follow'
      path: '/api/extension/follow'
      fullPath: '/api/extension/follow'
      preLoaderRoute: typeof ApiExtensionFollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/narration': {
      id: '/api/extension/narration'
      path: '/api/extension/narration'
      fullPath: '/api/extension/narration'
      preLoaderRoute: typeof ApiExtensionNarrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/recommend': {
      id: '/api/extension/recommend'
      path: '/api/extension/recommend'
      fullPath: '/api/extension/recommend'
      preLoaderRoute: typeof ApiExtensionRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/resolve': {
      id: '/api/extension/resolve'
      path: '/api/extension/resolve'
      fullPath: '/api/extension/resolve'
      preLoaderRoute: typeof ApiExtensionResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/session': {
      id: '/api/extension/session'
      path: '/api/extension/session'
      fullPath: '/api/extension/session'
      preLoaderRoute: typeof ApiExtensionSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/article': {
      id: '/api/og/article'
      path: '/api/og/article'
      fullPath: '/api/og/article'
      preLoaderRoute: typeof ApiOgArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/collection': {
      id: '/api/og/collection'
      path: '/api/og/collection'
      fullPath: '/api/og/collection'
      preLoaderRoute: typeof ApiOgCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/list': {
      id: '/api/og/list'
      path: '/api/og/list'
      fullPath: '/api/og/list'
      preLoaderRoute: typeof ApiOgListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/profile': {
      id: '/api/og/profile'
      path: '/api/og/profile'
      fullPath: '/api/og/profile'
      preLoaderRoute: typeof ApiOgProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/publication': {
      id: '/api/og/publication'
      path: '/api/og/publication'
      fullPath: '/api/og/publication'
      preLoaderRoute: typeof ApiOgPublicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/quote': {
      id: '/api/og/quote'
      path: '/api/og/quote'
      fullPath: '/api/og/quote'
      preLoaderRoute: typeof ApiOgQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/site': {
      id: '/api/og/site'
      path: '/api/og/site'
      fullPath: '/api/og/site'
      preLoaderRoute: typeof ApiOgSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$did/$rkey': {
      id: '/collection/$did/$rkey'
      path: '/collection/$did/$rkey'
      fullPath: '/collection/$did/$rkey'
      preLoaderRoute: typeof CollectionDidRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/latest/$did': {
      id: '/feed/latest/$did'
      path: '/feed/latest/$did'
      fullPath: '/feed/latest/$did'
      preLoaderRoute: typeof FeedLatestDidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/tag/$tag': {
      id: '/feed/tag/$tag'
      path: '/feed/tag/$tag'
      fullPath: '/feed/tag/$tag'
      preLoaderRoute: typeof FeedTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/u/$did': {
      id: '/feed/u/$did'
      path: '/feed/u/$did'
      fullPath: '/feed/u/$did'
      preLoaderRoute: typeof FeedUDidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe-login/$did/$rkey': {
      id: '/subscribe-login/$did/$rkey'
      path: '/subscribe-login/$did/$rkey'
      fullPath: '/subscribe-login/$did/$rkey'
      preLoaderRoute: typeof SubscribeLoginDidRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/$did/$rkey': {
      id: '/subscribe/$did/$rkey'
      path: '/subscribe/$did/$rkey'
      fullPath: '/subscribe/$did/$rkey'
      preLoaderRoute: typeof SubscribeDidRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/a/$did/$rkey': {
      id: '/_layout/a/$did/$rkey'
      path: '/a/$did/$rkey'
      fullPath: '/a/$did/$rkey'
      preLoaderRoute: typeof LayoutADidRkeyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/collections/edit/$rkey': {
      id: '/_layout/collections/edit/$rkey'
      path: '/edit/$rkey'
      fullPath: '/collections/edit/$rkey'
      preLoaderRoute: typeof LayoutCollectionsEditRkeyRouteImport
      parentRoute: typeof LayoutCollectionsRoute
    }
    '/_layout/l/$did/$rkey': {
      id: '/_layout/l/$did/$rkey'
      path: '/l/$did/$rkey'
      fullPath: '/l/$did/$rkey'
      preLoaderRoute: typeof LayoutLDidRkeyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/p/$did/$rkey': {
      id: '/_layout/p/$did/$rkey'
      path: '/p/$did/$rkey'
      fullPath: '/p/$did/$rkey'
      preLoaderRoute: typeof LayoutPDidRkeyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/auth/atproto/authorize': {
      id: '/api/auth/atproto/authorize'
      path: '/api/auth/atproto/authorize'
      fullPath: '/api/auth/atproto/authorize'
      preLoaderRoute: typeof ApiAuthAtprotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/callback': {
      id: '/api/auth/atproto/callback'
      path: '/api/auth/atproto/callback'
      fullPath: '/api/auth/atproto/callback'
      preLoaderRoute: typeof ApiAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/jwks.json': {
      id: '/api/auth/atproto/jwks.json'
      path: '/api/auth/atproto/jwks.json'
      fullPath: '/api/auth/atproto/jwks.json'
      preLoaderRoute: typeof ApiAuthAtprotoJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/metadata.json': {
      id: '/api/auth/atproto/metadata.json'
      path: '/api/auth/atproto/metadata.json'
      fullPath: '/api/auth/atproto/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/signup': {
      id: '/api/auth/atproto/signup'
      path: '/api/auth/atproto/signup'
      fullPath: '/api/auth/atproto/signup'
      preLoaderRoute: typeof ApiAuthAtprotoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/page/$slug': {
      id: '/api/og/page/$slug'
      path: '/api/og/page/$slug'
      fullPath: '/api/og/page/$slug'
      preLoaderRoute: typeof ApiOgPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/subscribe/$did/$rkey': {
      id: '/embed/subscribe/$did/$rkey'
      path: '/embed/subscribe/$did/$rkey'
      fullPath: '/embed/subscribe/$did/$rkey'
      preLoaderRoute: typeof EmbedSubscribeDidRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/collection/$did/$rkey': {
      id: '/feed/collection/$did/$rkey'
      path: '/feed/collection/$did/$rkey'
      fullPath: '/feed/collection/$did/$rkey'
      preLoaderRoute: typeof FeedCollectionDidRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/l/$did/$rkey': {
      id: '/feed/l/$did/$rkey'
      path: '/feed/l/$did/$rkey'
      fullPath: '/feed/l/$did/$rkey'
      preLoaderRoute: typeof FeedLDidRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/p/$did/$rkey': {
      id: '/feed/p/$did/$rkey'
      path: '/feed/p/$did/$rkey'
      fullPath: '/feed/p/$did/$rkey'
      preLoaderRoute: typeof FeedPDidRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/review/callback': {
      id: '/api/auth/atproto/review/callback'
      path: '/api/auth/atproto/review/callback'
      fullPath: '/api/auth/atproto/review/callback'
      preLoaderRoute: typeof ApiAuthAtprotoReviewCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/review/metadata.json': {
      id: '/api/auth/atproto/review/metadata.json'
      path: '/api/auth/atproto/review/metadata.json'
      fullPath: '/api/auth/atproto/review/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoReviewMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsHeaderLayoutRouteChildren {
  DocsHeaderLayoutDocsApiRoute: typeof DocsHeaderLayoutDocsApiRoute
  DocsHeaderLayoutDocsIntroductionRoute: typeof DocsHeaderLayoutDocsIntroductionRoute
  DocsHeaderLayoutDocsLexiconsRoute: typeof DocsHeaderLayoutDocsLexiconsRoute
  DocsHeaderLayoutDocsPublishingRoute: typeof DocsHeaderLayoutDocsPublishingRoute
  DocsHeaderLayoutDocsRenderersRoute: typeof DocsHeaderLayoutDocsRenderersRoute
}

const DocsHeaderLayoutRouteChildren: DocsHeaderLayoutRouteChildren = {
  DocsHeaderLayoutDocsApiRoute: DocsHeaderLayoutDocsApiRoute,
  DocsHeaderLayoutDocsIntroductionRoute: DocsHeaderLayoutDocsIntroductionRoute,
  DocsHeaderLayoutDocsLexiconsRoute: DocsHeaderLayoutDocsLexiconsRoute,
  DocsHeaderLayoutDocsPublishingRoute: DocsHeaderLayoutDocsPublishingRoute,
  DocsHeaderLayoutDocsRenderersRoute: DocsHeaderLayoutDocsRenderersRoute,
}

const DocsHeaderLayoutRouteWithChildren =
  DocsHeaderLayoutRoute._addFileChildren(DocsHeaderLayoutRouteChildren)

interface LayoutCollectionsRouteChildren {
  LayoutCollectionsNewRoute: typeof LayoutCollectionsNewRoute
  LayoutCollectionsIndexRoute: typeof LayoutCollectionsIndexRoute
  LayoutCollectionsEditRkeyRoute: typeof LayoutCollectionsEditRkeyRoute
}

const LayoutCollectionsRouteChildren: LayoutCollectionsRouteChildren = {
  LayoutCollectionsNewRoute: LayoutCollectionsNewRoute,
  LayoutCollectionsIndexRoute: LayoutCollectionsIndexRoute,
  LayoutCollectionsEditRkeyRoute: LayoutCollectionsEditRkeyRoute,
}

const LayoutCollectionsRouteWithChildren =
  LayoutCollectionsRoute._addFileChildren(LayoutCollectionsRouteChildren)

interface LayoutPrivacyRouteChildren {
  LayoutPrivacyExtensionRoute: typeof LayoutPrivacyExtensionRoute
}

const LayoutPrivacyRouteChildren: LayoutPrivacyRouteChildren = {
  LayoutPrivacyExtensionRoute: LayoutPrivacyExtensionRoute,
}

const LayoutPrivacyRouteWithChildren = LayoutPrivacyRoute._addFileChildren(
  LayoutPrivacyRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutCollectionsRoute: typeof LayoutCollectionsRouteWithChildren
  LayoutDiscoverRoute: typeof LayoutDiscoverRoute
  LayoutFriendsRoute: typeof LayoutFriendsRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutLatestRoute: typeof LayoutLatestRoute
  LayoutLikesRoute: typeof LayoutLikesRoute
  LayoutPrivacyRoute: typeof LayoutPrivacyRouteWithChildren
  LayoutRecommendedRoute: typeof LayoutRecommendedRoute
  LayoutSavedRoute: typeof LayoutSavedRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutTermsRoute: typeof LayoutTermsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFeedbackReturnRoute: typeof LayoutFeedbackReturnRoute
  LayoutLabelersDidRoute: typeof LayoutLabelersDidRoute
  LayoutTagTagRoute: typeof LayoutTagTagRoute
  LayoutUDidRoute: typeof LayoutUDidRoute
  LayoutFeedbackIndexRoute: typeof LayoutFeedbackIndexRoute
  LayoutLabelersIndexRoute: typeof LayoutLabelersIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutADidRkeyRoute: typeof LayoutADidRkeyRoute
  LayoutLDidRkeyRoute: typeof LayoutLDidRkeyRoute
  LayoutPDidRkeyRoute: typeof LayoutPDidRkeyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutCollectionsRoute: LayoutCollectionsRouteWithChildren,
  LayoutDiscoverRoute: LayoutDiscoverRoute,
  LayoutFriendsRoute: LayoutFriendsRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutLatestRoute: LayoutLatestRoute,
  LayoutLikesRoute: LayoutLikesRoute,
  LayoutPrivacyRoute: LayoutPrivacyRouteWithChildren,
  LayoutRecommendedRoute: LayoutRecommendedRoute,
  LayoutSavedRoute: LayoutSavedRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutTermsRoute: LayoutTermsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFeedbackReturnRoute: LayoutFeedbackReturnRoute,
  LayoutLabelersDidRoute: LayoutLabelersDidRoute,
  LayoutTagTagRoute: LayoutTagTagRoute,
  LayoutUDidRoute: LayoutUDidRoute,
  LayoutFeedbackIndexRoute: LayoutFeedbackIndexRoute,
  LayoutLabelersIndexRoute: LayoutLabelersIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutADidRkeyRoute: LayoutADidRkeyRoute,
  LayoutLDidRkeyRoute: LayoutLDidRkeyRoute,
  LayoutPDidRkeyRoute: LayoutPDidRkeyRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DocsHeaderLayoutRoute: DocsHeaderLayoutRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  DevDigestRoute: DevDigestRoute,
  DevRtlRoute: DevRtlRoute,
  DevWelcomeEmailRoute: DevWelcomeEmailRoute,
  ExtensionConnectedRoute: ExtensionConnectedRoute,
  ReviewThanksRoute: ReviewThanksRoute,
  XrpcSplatRoute: XrpcSplatRoute,
  ApiBskyPostRoute: ApiBskyPostRoute,
  ApiDevDigestPreviewRoute: ApiDevDigestPreviewRoute,
  ApiDevWelcomePreviewRoute: ApiDevWelcomePreviewRoute,
  ApiDigestPreviewRoute: ApiDigestPreviewRoute,
  ApiDigestUnsubscribeRoute: ApiDigestUnsubscribeRoute,
  ApiExtensionBookmarkRoute: ApiExtensionBookmarkRoute,
  ApiExtensionDiscussionRoute: ApiExtensionDiscussionRoute,
  ApiExtensionFollowRoute: ApiExtensionFollowRoute,
  ApiExtensionNarrationRoute: ApiExtensionNarrationRoute,
  ApiExtensionRecommendRoute: ApiExtensionRecommendRoute,
  ApiExtensionResolveRoute: ApiExtensionResolveRoute,
  ApiExtensionSessionRoute: ApiExtensionSessionRoute,
  ApiOgArticleRoute: ApiOgArticleRoute,
  ApiOgCollectionRoute: ApiOgCollectionRoute,
  ApiOgListRoute: ApiOgListRoute,
  ApiOgProfileRoute: ApiOgProfileRoute,
  ApiOgPublicationRoute: ApiOgPublicationRoute,
  ApiOgQuoteRoute: ApiOgQuoteRoute,
  ApiOgSiteRoute: ApiOgSiteRoute,
  CollectionDidRkeyRoute: CollectionDidRkeyRoute,
  FeedLatestDidRoute: FeedLatestDidRoute,
  FeedTagTagRoute: FeedTagTagRoute,
  FeedUDidRoute: FeedUDidRoute,
  SubscribeLoginDidRkeyRoute: SubscribeLoginDidRkeyRoute,
  SubscribeDidRkeyRoute: SubscribeDidRkeyRoute,
  ApiAuthAtprotoAuthorizeRoute: ApiAuthAtprotoAuthorizeRoute,
  ApiAuthAtprotoCallbackRoute: ApiAuthAtprotoCallbackRoute,
  ApiAuthAtprotoJwksDotjsonRoute: ApiAuthAtprotoJwksDotjsonRoute,
  ApiAuthAtprotoMetadataDotjsonRoute: ApiAuthAtprotoMetadataDotjsonRoute,
  ApiAuthAtprotoSignupRoute: ApiAuthAtprotoSignupRoute,
  ApiOgPageSlugRoute: ApiOgPageSlugRoute,
  EmbedSubscribeDidRkeyRoute: EmbedSubscribeDidRkeyRoute,
  FeedCollectionDidRkeyRoute: FeedCollectionDidRkeyRoute,
  FeedLDidRkeyRoute: FeedLDidRkeyRoute,
  FeedPDidRkeyRoute: FeedPDidRkeyRoute,
  ApiAuthAtprotoReviewCallbackRoute: ApiAuthAtprotoReviewCallbackRoute,
  ApiAuthAtprotoReviewMetadataDotjsonRoute:
    ApiAuthAtprotoReviewMetadataDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
